complete
Viktor-Chernysh/nodejs-homework-REST-API pull request #2
Opened 2021-12-26 16:40 UTC by Viktor-Chernysh

Проверьте пожалуйста

2021-12-27 19:54 UTC, KirillKulakow commented on .env
> +DB_URI=mongodb+srv://viktor:hw03@cluster0.xrybl.mongodb.net/db-contacts
удалить из гита и добавить файл в gitignore

2021-12-27 19:54 UTC, KirillKulakow commented on .vscode/launch.json
> +{
зачем этот файл в гите? удалить и добавить в gitignore

2021-12-27 19:56 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: "success", code: HttpCode.OK, data: { ...contacts } });
смысл данной строки `data: { ...contacts }` ? объясни мне в слак

2021-12-27 20:00 UTC, KirillKulakow requested changes
Need fix

2021-12-28 10:19 UTC, Viktor-Chernysh commented on .env
> +DB_URI=mongodb+srv://viktor:hw03@cluster0.xrybl.mongodb.net/db-contacts
добавил в игнор

2021-12-28 10:20 UTC, Viktor-Chernysh commented on .vscode/launch.json
> +{
добавил в игнор

2021-12-28 10:20 UTC, Viktor-Chernysh commented on controllers/contacts/index.js
> +    .json({ status: "success", code: HttpCode.OK, data: { ...contacts } });
в слак написал

2021-12-28 20:07 UTC, KirillKulakow approved these changes

2021-12-28 20:54 UTC, merged