add autherization
Viktor-Chernysh/nodejs-homework-REST-API pull request #3
Opened 2022-01-06 13:27 UTC by Viktor-Chernysh

Оставил пару комментов- как шпаргалку для себя

2022-01-06 20:31 UTC, KirillKulakow commented on controllers/auth/index.js
> +
не хватает последнего шага дз

2022-01-06 20:33 UTC, KirillKulakow requested changes
Need fix

2022-01-07 11:50 UTC, Viktor-Chernysh commented on controllers/auth/index.js
> +
Добавил current

2022-01-10 20:59 UTC, KirillKulakow approved these changes

2022-01-11 09:50 UTC, merged